Module modDTVarDT
    Public Sub cpm_DT_eIELDMI1(ByVal wp_DT As DataTable)
        With wg_eIELDMI1.eIEDMI
            .nId = IIf(Not IsDBNull(wp_DT.Rows(0).Item(0)), wp_DT.Rows(0).Item(0), 0)
            .sCodItm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(1)), wp_DT.Rows(0).Item(1), "")
            .sCodBar = IIf(Not IsDBNull(wp_DT.Rows(0).Item(2)), wp_DT.Rows(0).Item(2), "")
            .sNomItm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(3)), wp_DT.Rows(0).Item(3), "")
            .sNomAlt = IIf(Not IsDBNull(wp_DT.Rows(0).Item(4)), wp_DT.Rows(0).Item(4), "")
            .sClsItm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(5)), wp_DT.Rows(0).Item(5), "")
            .sCodGrp = IIf(Not IsDBNull(wp_DT.Rows(0).Item(6)), wp_DT.Rows(0).Item(6), "")
            .sCodSgr = IIf(Not IsDBNull(wp_DT.Rows(0).Item(7)), wp_DT.Rows(0).Item(7), "")
            .bItmInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(8)), wp_DT.Rows(0).Item(8), False)
            .bItmVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(9)), wp_DT.Rows(0).Item(9), False)
            .bItmCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(10)), wp_DT.Rows(0).Item(10), False)
            .bIndIVA = IIf(Not IsDBNull(wp_DT.Rows(0).Item(11)), wp_DT.Rows(0).Item(11), False)
            .sCodAlt = IIf(Not IsDBNull(wp_DT.Rows(0).Item(12)), wp_DT.Rows(0).Item(12), "")
            .sTipGes = IIf(Not IsDBNull(wp_DT.Rows(0).Item(13)), wp_DT.Rows(0).Item(13), "")
            .bItmAct = IIf(Not IsDBNull(wp_DT.Rows(0).Item(14)), wp_DT.Rows(0).Item(14), False)
            .bItmIna = IIf(Not IsDBNull(wp_DT.Rows(0).Item(15)), wp_DT.Rows(0).Item(15), False)
            .sCodTerPrv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(16)), wp_DT.Rows(0).Item(16), "")
            .sCodTerFte = IIf(Not IsDBNull(wp_DT.Rows(0).Item(17)), wp_DT.Rows(0).Item(17), "")
            .sCodItmFte = IIf(Not IsDBNull(wp_DT.Rows(0).Item(18)), wp_DT.Rows(0).Item(18), "")
            .sUniMedCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(19)), wp_DT.Rows(0).Item(19), "")
            .nCanUniCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(20)), wp_DT.Rows(0).Item(20), 0)
            .sUniEmpCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(21)), wp_DT.Rows(0).Item(21), "")
            .nCanUniECom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(21)), wp_DT.Rows(0).Item(21), 0)
            .sCodItoCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(23)), wp_DT.Rows(0).Item(23), "")
            .sUniMedVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(24)), wp_DT.Rows(0).Item(24), "")
            .nCanUniVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(25)), wp_DT.Rows(0).Item(25), 0)
            .sUniEmpVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(26)), wp_DT.Rows(0).Item(26), "")
            .nCanUniEVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(27)), wp_DT.Rows(0).Item(27), 0)
            .sCodItoVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(28)), wp_DT.Rows(0).Item(28), "")
            .sCriCtaCbe = IIf(Not IsDBNull(wp_DT.Rows(0).Item(29)), wp_DT.Rows(0).Item(29), "")
            .sUniMedInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(30)), wp_DT.Rows(0).Item(30), "")
            .sMetVlz = IIf(Not IsDBNull(wp_DT.Rows(0).Item(31)), wp_DT.Rows(0).Item(31), "")
            .nCosItm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(32)), wp_DT.Rows(0).Item(32), "")
            .sCodAlm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(33)), wp_DT.Rows(0).Item(33), "")
            .nSdoInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(34)), wp_DT.Rows(0).Item(34), 0)
            .sIvaCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(35)), wp_DT.Rows(0).Item(35), "")
            .sIvaVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(36)), wp_DT.Rows(0).Item(36), "")
        End With
        With wg_eIELDMI1.eILDMI1
            .nId = IIf(Not IsDBNull(wp_DT.Rows(0).Item(37)), wp_DT.Rows(0).Item(37), "")
            .sCodItm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(38)), wp_DT.Rows(0).Item(38), "")
            .sCodAlm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(39)), wp_DT.Rows(0).Item(39), "")
            .nCanMin = IIf(Not IsDBNull(wp_DT.Rows(0).Item(40)), wp_DT.Rows(0).Item(40), 0)
            .nCanMax = IIf(Not IsDBNull(wp_DT.Rows(0).Item(41)), wp_DT.Rows(0).Item(41), 0)
            .nOrdMin = IIf(Not IsDBNull(wp_DT.Rows(0).Item(42)), wp_DT.Rows(0).Item(42), 0)
            .nSdoAlm = IIf(Not IsDBNull(wp_DT.Rows(0).Item(43)), wp_DT.Rows(0).Item(43), 0)
            .nPreUni = IIf(Not IsDBNull(wp_DT.Rows(0).Item(44)), wp_DT.Rows(0).Item(44), 0)
            .nVlrTot = IIf(Not IsDBNull(wp_DT.Rows(0).Item(45)), wp_DT.Rows(0).Item(45), 0)
            .sCtaInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(46)), wp_DT.Rows(0).Item(46), "")
            .sCtaCosVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(47)), wp_DT.Rows(0).Item(47), "")
            .sCtaTrs = IIf(Not IsDBNull(wp_DT.Rows(0).Item(48)), wp_DT.Rows(0).Item(48), "")
            .sCtaIng = IIf(Not IsDBNull(wp_DT.Rows(0).Item(49)), wp_DT.Rows(0).Item(49), "")
            .sCtaDevVta = IIf(Not IsDBNull(wp_DT.Rows(0).Item(50)), wp_DT.Rows(0).Item(50), "")
            .sCtaGto = IIf(Not IsDBNull(wp_DT.Rows(0).Item(51)), wp_DT.Rows(0).Item(51), "")
            .sCtaDot = IIf(Not IsDBNull(wp_DT.Rows(0).Item(52)), wp_DT.Rows(0).Item(52), "")
            .sCtaDifPre = IIf(Not IsDBNull(wp_DT.Rows(0).Item(53)), wp_DT.Rows(0).Item(53), "")
            .sCtaDsv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(54)), wp_DT.Rows(0).Item(54), "")
            .sCtaRev = IIf(Not IsDBNull(wp_DT.Rows(0).Item(55)), wp_DT.Rows(0).Item(55), "")
            .sCtaAumInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(56)), wp_DT.Rows(0).Item(56), "")
            .sCtaRedInv = IIf(Not IsDBNull(wp_DT.Rows(0).Item(57)), wp_DT.Rows(0).Item(57), "")
            .sCtaCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(58)), wp_DT.Rows(0).Item(58), "")
            .sCtaDevCom = IIf(Not IsDBNull(wp_DT.Rows(0).Item(59)), wp_DT.Rows(0).Item(59), "")
        End With
    End Sub

End Module
